# Generated by Django 4.2.16 on 2024-11-10 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_pto_created_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PTO',
            new_name='Item',
        ),
    ]
